# Generated by Django 6.0.4 on 2026-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=32, unique=True)),
                ('categorie', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('langue', models.CharField(default='Français', max_length=50)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('quantite_totale', models.PositiveIntegerField(default=1)),
                ('quantite_disponible', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
    ]
