# Generated by Django 6.0.4 on 2026-05-03 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_id', models.PositiveIntegerField()),
                ('utilisateur_nom', models.CharField(max_length=255)),
                ('livre_id', models.PositiveIntegerField()),
                ('livre_titre', models.CharField(max_length=255)),
                ('date_emprunt', models.DateField(default=django.utils.timezone.now)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('retourne', 'Retourné'), ('en_retard', 'En retard')], default='en_cours', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_emprunt', '-cree_le'],
            },
        ),
    ]
