# Generated by Django 6.0.4 on 2026-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurBibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('departement', models.CharField(blank=True, max_length=120)),
                ('numero_carte', models.CharField(max_length=60, unique=True)),
                ('type_utilisateur', models.CharField(choices=[('etudiant', 'Étudiant'), ('professeur', 'Professeur'), ('personnel', 'Personnel')], default='etudiant', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
